import Head from "next/head";
import styles from "../styles/Home.module.css";
import Message from "../components/Message";
import { collection, getDocs, orderBy, query } from "firebase/firestore";
import { db } from "../utils/firebase";
import React, { useEffect, useState } from "react";
import Spinner from "../components/Spinner";

export default function Home() {
  const [getAllPost, setgetAllPost] = useState([]);
  const getPosts = async () => {
    const q = query(collection(db, "posts"), orderBy("timestamp", "desc"));

    const querySnapshot = await getDocs(q);
    const data = [];
    querySnapshot.forEach((doc) => {
      data.push({ ...doc.data(), id: doc.id });
    });

    setgetAllPost(data);
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" mt-20">
        <p className=" text-lg font-semibold">
          See what other people are saying
        </p>
        {getAllPost.length == 0 ? (
          <Spinner />
        ) : (
          getAllPost.map((post) => <Message key={post.id} {...post}></Message>)
        )}
      </div>
    </div>
  );
}
